apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: web-solutions
data:
  index.html: |
    <!doctype html>
    <html>
    <head><meta charset="utf-8"><title>Nginx - Web Solutions</title></head>
    <body>
      <h1>Nginx - Web Solutions</h1>
      <p>Servidor: Nginx</p>
      <p>Porta externa: 8080</p>
    </body>
    </html>
