apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index
  namespace: web-solutions
data:
  index.html: |
    <!doctype html>
    <html>
    <head><meta charset="utf-8"><title>Apache - Web Solutions</title></head>
    <body>
      <h1>Apache HTTPD - Web Solutions</h1>
      <p>Servidor: Apache HTTPD</p>
      <p>Porta externa: 8081</p>
    </body>
    </html>
