apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: web-solutions
  labels:
    app: apache
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
